# Generated by Django 2.0 on 2018-02-12 05:19

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line_1', models.CharField(blank=True, max_length=60)),
                ('address_line_2', models.CharField(blank=True, max_length=60)),
                ('city', models.CharField(blank=True, max_length=40)),
                ('state', models.CharField(blank=True, max_length=20, verbose_name='State/Province')),
                ('country', models.CharField(blank=True, max_length=50)),
                ('postal', models.CharField(blank=True, max_length=10)),
                ('formatted_address', models.CharField(blank=True, max_length=245)),
                ('lat', models.FloatField(blank=True)),
                ('lng', models.FloatField(blank=True)),
                ('name', models.CharField(max_length=40)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Arena',
            fields=[
                ('venue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='venues.Venue')),
                ('manager', models.CharField(help_text='Contact person at the arena', max_length=40)),
            ],
            options={
                'abstract': False,
            },
            bases=('venues.venue',),
        ),
    ]
