# Generated by Django 2.0 on 2018-03-05 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arena',
            name='manager',
            field=models.CharField(blank=True, help_text='Contact person at the arena', max_length=40),
        ),
        migrations.AlterField(
            model_name='venue',
            name='formatted_address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
