# Generated by Django 3.0.5 on 2020-04-08 23:21

from django.db import migrations, models
import main.utils


class Migration(migrations.Migration):

    dependencies = [
        ('seasons', '0002_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='goal_horn',
            field=models.FileField(blank=True, upload_to=main.utils.slugified_file_location),
        ),
    ]
