# Generated by Django 4.0.6 on 2022-07-11 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seasons', '0003_team_goal_horn'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
