# Generated by Django 4.0.6 on 2022-07-11 02:12

from django.db import migrations, models
import main.utils


class Migration(migrations.Migration):

    dependencies = [
        ('seasons', '0004_team_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['pk']},
        ),
        migrations.AddField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, upload_to=main.utils.slugified_file_location),
        ),
    ]
