# Generated by Django 2.1.7 on 2019-10-08 23:23

import logging
from django.conf import settings
from django.contrib.auth import get_user_model
from django.db import migrations

logger = logging.getLogger('django')

User = get_user_model()

SU_USERNAME = 'mnlhl'
SU_PASSWORD = 'earnthekeg'


def create_development_superuser(apps, schema_editor):
    if settings.ENVIRONMENT in ['local', 'dev', 'develop', 'development']:
        superuser = User.objects.create_superuser(
            username=SU_USERNAME, password=SU_PASSWORD, email=None)
        logger.info('Superuser {superuser} created'.format(superuser=superuser))
    else:
        logger.info('Superuser not created in {env} environment'.format(env=settings.ENVIRONMENT))


def delete_development_superuser(apps, schema_editor):
    # User = get_user_model()
    superuser = User.objects.filter(username=SU_USERNAME).first()
    if superuser:
        logger.info('Deleting superuser {superuser}'.format(superuser=superuser))
        superuser.delete()
    else:
        logger.info('Superuser not found, did not delete'.format(env=settings.ENVIRONMENT))


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_development_superuser, delete_development_superuser),
    ]
